### ISSUE TITLE
dagger-reflect does not resolve Provider/Lazy indirection based dependency cycles

### ISSUE THREAD

**Issue by matejdro** [JakeWharton/dagger-reflect#175]
Running following code:

```kotlin
@Singleton
@Component(modules = [MainModule::class])
interface MainComponent {
    fun provideFactory(): TestFactory
}

@Module
abstract class MainModule {
    @Binds
    @IntoMap
    @ClassKey(TestClassA::class)
    abstract fun bindA(testClassA: TestClassA): Any
}

@Singleton
class TestFactory @Inject constructor(
    private val providers: Map<@JvmSuppressWildcards Class<*>, @JvmSuppressWildcards Provider<Any>>
) {
    fun createA(): TestClassA {
        @Suppress("UNCHECKED_CAST")
        return (providers[TestClassA::class.java] as Provider<TestClassA>).get()
    }
}

class TestClassA @Inject constructor(val factory: TestFactory)

fun main() {
    Dagger.create(MainComponent::class.java)
        .provideFactory()
}
```

With:

```
implementation 'com.google.dagger:dagger:2.24'

// Snapshot fetched on Mon Oct 7 2019 8:00:00 UTC>
implementation 'com.jakewharton.dagger:dagger-reflect:0.2.0-SNAPSHOT'
```

Will result in a following crash:

```
Exception in thread "main" java.lang.IllegalStateException: Dependency cycle for test.TestFactory
 * Requested: test.TestFactory
     from dagger.reflect.UnlinkedScopedBinding@66cd51c3
 * Requested: java.util.Map<java.lang.Class<?>, javax.inject.Provider<java.lang.Object>>
     from Map{class test.TestClassA=@Binds[test.MainModule.bindA(…)]}
 * Requested: test.TestClassA
     from @Inject[test.TestClassA.<init>(…)]
 * Requested: test.TestFactory
     which forms a cycle.
	at dagger.reflect.Linker.failure(Linker.java:45)
	at dagger.reflect.Linker.link(Linker.java:32)
	at dagger.reflect.Scope.link(Scope.java:145)
	at dagger.reflect.Scope.findExistingBinding(Scope.java:103)
	at dagger.reflect.Scope.findBinding(Scope.java:74)
	at dagger.reflect.Linker.find(Linker.java:27)
	at dagger.reflect.Linker.get(Linker.java:18)
	at dagger.reflect.UnlinkedJustInTimeBinding.link(UnlinkedJustInTimeBinding.java:38)
	at dagger.reflect.Linker.link(Linker.java:35)
	at dagger.reflect.Scope.link(Scope.java:145)
	at dagger.reflect.Scope.putJitBinding(Scope.java:138)
	at dagger.reflect.Scope.findBinding(Scope.java:81)
	at dagger.reflect.Linker.find(Linker.java:27)
	at dagger.reflect.Linker.get(Linker.java:18)
	at dagger.reflect.UnlinkedBindsBinding.link(UnlinkedBindsBinding.java:26)
	at dagger.reflect.UnlinkedMapOfProviderBinding.link(UnlinkedMapOfProviderBinding.java:20)
	at dagger.reflect.Linker.link(Linker.java:35)
	at dagger.reflect.Scope.link(Scope.java:145)
	at dagger.reflect.Scope.findExistingBinding(Scope.java:103)
	at dagger.reflect.Scope.findBinding(Scope.java:74)
	at dagger.reflect.Linker.find(Linker.java:27)
	at dagger.reflect.Linker.get(Linker.java:18)
	at dagger.reflect.UnlinkedJustInTimeBinding.link(UnlinkedJustInTimeBinding.java:38)
	at dagger.reflect.UnlinkedScopedBinding.link(UnlinkedScopedBinding.java:14)
	at dagger.reflect.Linker.link(Linker.java:35)
	at dagger.reflect.Scope.link(Scope.java:145)
	at dagger.reflect.Scope.putJitBinding(Scope.java:138)
	at dagger.reflect.Scope.findBinding(Scope.java:81)
	at dagger.reflect.Scope.getBinding(Scope.java:44)
	at dagger.reflect.ComponentInvocationHandler.createMethodInvocationHandler(ComponentInvocationHandler.java:99)
	at dagger.reflect.ComponentInvocationHandler.invoke(ComponentInvocationHandler.java:64)
	at com.sun.proxy.$Proxy14.provideFactory(Unknown Source)
	at test.AppComponentKt.main(AppComponent.kt:38)
	at test.AppComponentKt.main(AppComponent.kt)
```

Kapt dagger handles this code fine.

**Comment by gfreivasc** [comment]
This looks like it's directly related to the multibinding provider map scenario. Testing this against depending on the bound provider or the actual provider won't fail.

```java
@Module
public class Module1 {
  @Binds
  Object bindA(TestClassA a)
}

class TestFactory {
  public final Provider<Object> providerObject;
  public final Provider<TestClassA> providerA;

  @Inject
  TestFactory(Provider<Object> providerObject, Provider<TestClassA> providerA) {
    this.providerObject = providerObject;
    this.providerA = providerA;
  }
}
```

This works as expected, just as it does in dagger codegen.

**Comment by alexjlockwood** [comment]
Seems like it was a known issue at the time this PR was merged: https://github.com/JakeWharton/dagger-reflect/pull/111/files#diff-bbe446ece965bf564fc9033c303bce89R62

Maybe @runningcode recalls the specific issue that was preventing this from being fixed.

**Comment by JakeWharton** [comment]
I'm going to spend an hour on this. I suspect at least 20m will be paging back in a bunch of context into my brain, but maybe I'll be able to spot the problem.

**Comment by JakeWharton** [comment]
Alright I think I found it...
