### ISSUE TITLE
Multibinds is not supported

### ISSUE THREAD

**Issue by kokeroulis** [JakeWharton/dagger-reflect#177]
Version: **master branch**

Currently the multi binds annotation is not supported.
Assuming that we have the following **component**

```kotlin
@Component(modules = { MapMultiBinds.MultiBindsModule.class })
interface MapMultiBinds {
    Thing thing();

    @dagger.Module
    abstract class MultiBindsModule {
        @Multibinds
        abstract Map<String, Integer> getEmptyStringAndInteger();
    }

    class Thing {

        private final Map<String, Integer> stringIntegerMap;

        @Inject
        public Thing(Map<String, Integer> stringIntegerMap) {
            this.stringIntegerMap = stringIntegerMap;
        }

        public Map<String, Integer> getStringIntegerMap() {
            return stringIntegerMap;
        }
    }
}
```

And we have the following **unit test**

```kotlin
  @Test
  public void mapMultiBinds() {
    MapMultiBinds.Thing thing = backend
                    .create(MapMultiBinds.class)
                    .thing();

    assertThat(thing.getStringIntegerMap()).isEmpty();
  }
```

Dagger reflect fails with the following exception while dagger with annotation processing works fine

```
java.lang.IllegalStateException: Missing binding for java.util.Map<java.lang.String, java.lang.Integer>
 * Requested: com.example.MapMultiBinds$Thing
     from @Inject[com.example.MapMultiBinds$Thing.<init>(…)]
 * Requested: java.util.Map<java.lang.String, java.lang.Integer>
     which was not found.

	at dagger.reflect.Linker.failure(Linker.java:45)
	at dagger.reflect.Linker.get(Linker.java:22)
	at dagger.reflect.UnlinkedJustInTimeBinding.link(UnlinkedJustInTimeBinding.java:38)
	at dagger.reflect.Linker.link(Linker.java:35)
	at dagger.reflect.Scope.link(Scope.java:150)
	at dagger.reflect.Scope.putJitBinding(Scope.java:143)
	at dagger.reflect.Scope.findBinding(Scope.java:86)
	at dagger.reflect.Scope.getBinding(Scope.java:49)
	at dagger.reflect.ComponentInvocationHandler.createMethodInvocationHandler(ComponentInvocationHandler.java:99)
	at dagger.reflect.ComponentInvocationHandler.invoke(ComponentInvocationHandler.java:64)
	at com.example.$Proxy14.thing(Unknown Source)
	at com.example.IntegrationTest.mapMultiBinds(IntegrationTest.java:1568)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:365)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:330)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:78)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:328)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:65)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:292)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:305)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by JakeWharton** [comment]
I had no idea this annotation even existed!
