### ISSUE TITLE
JIT binding depending on JIT binding fails

### ISSUE THREAD

**Issue by MaximPestryakov** [JakeWharton/dagger-reflect#97]
I have two classes:
```kotlin
class MyClass1 @Inject constructor(private val delegate: MyClass2)

class MyClass2 @Inject constructor()
```
And the component:
```kotlin
@Singleton
@Component
interface AppComponent {

    val myClass1: MyClass1

    val myClass2: MyClass2
}
```
When I'm trying to provide `MyClass1` like this:
```kotlin
val appComponent = DaggerAppComponent.create()
appComponent.myClass1.doSmth()
```
I got an exception: 
```
java.lang.IllegalStateException: Missing binding for sample.MyClass2
     * Requested: sample.MyClass1
         from @Inject[sample.MyClass1.<init>(…)]
     * Requested: sample.MyClass2
         which was not found.
        at dagger.reflect.Linker.failure(Linker.java:65)
        at dagger.reflect.Linker.get(Linker.java:26)
        at dagger.reflect.UnlinkedJustInTimeBinding.link(UnlinkedJustInTimeBinding.java:46)
        at dagger.reflect.Linker.performLinking(Linker.java:42)
        at dagger.reflect.Linker.link(Linker.java:11)
        at dagger.reflect.Scope.putJitBinding(Scope.java:85)
        at dagger.reflect.Scope.getBinding(Scope.java:33)
        at dagger.reflect.ComponentInvocationHandler.createMethodInvocationHandler(ComponentInvocationHandler.java:111)
        at dagger.reflect.ComponentInvocationHandler.invoke(ComponentInvocationHandler.java:61)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy4.getMyClass1(Unknown Source)
        ...
```

But when I provide `MyClass2` before providing `MyClass1`:
```kotlin
val appComponent = DaggerAppComponent.create()
appComponent.myClass2
appComponent.myClass1.doSmth()
```
or when I provide it in module:
```kotlin

@Module
object AppModule {

    @Provides
    @JvmStatic
    fun provideMyClass2() = MyClass2()
}
```
then everything is fine

**Comment by runningcode** [comment]
Will be fixed by: https://github.com/JakeWharton/dagger-reflect/pull/96

just need to do it properly :)
